#!/usr/bin/env python3
"""Regenerate README.md's source table from `sources_registry.py`, or check it.

    python3 check_sources.py            # rewrite the table in place
    python3 check_sources.py --check    # exit 1 if README.md has drifted

This exists because on 2026-09-25 that table was found to be wrong on four of
its eight rows, and its summary sentence inverted -- it told a sponsor that six
of eight sources were unread when six of eight had been read. The table is now
GENERATED, so it cannot drift from the registry; the registry is the only place
the fact is written.

Cheap and deterministic, so unlike `handover_numbers.py` this one belongs in
the pre-commit hook: it checks an INVARIANT BETWEEN DOCUMENTS, not a claim
about the world.
"""
import sys

import sources_registry

START = "<!-- BEGIN generated by check_sources.py -- edit sources_registry.py -->"
END = "<!-- END generated by check_sources.py -->"


def splice(text, block):
    if START not in text or END not in text:
        sys.exit("README.md is missing the generated-table markers")
    head = text[:text.index(START) + len(START)]
    tail = text[text.index(END):]
    return f"{head}\n{block}\n{tail}"


def main(argv):
    check = "--check" in argv
    with open("README.md", encoding="utf-8") as fh:
        text = fh.read()
    want = splice(text, sources_registry.render_table())
    if check:
        if want != text:
            print("README.md's source table has DRIFTED from "
                  "sources_registry.py. Run: python3 check_sources.py")
            return 1
        print("ok: README.md's source table matches sources_registry.py")
        return 0
    if want == text:
        print("up to date: README.md matches sources_registry.py")
        return 0
    with open("README.md", "w", encoding="utf-8") as fh:
        fh.write(want)
    print("rewrote README.md's source table from sources_registry.py")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
